###Decision Tree

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ds = pd.read_csv('/content/student_ml_practice_dataset.csv')

In [ ]:
ds.head()

   Student_ID    Name  Age Gender Course      City  Marks  Attendance Placed
0         101   Aarav   21   Male    MCA    Indore     78          82     No
1         102  Vivaan   22   Male    MCA    Bhopal     85          91    Yes
2         103  Aditya   20   Male    BCA     Satna     67          75     No
3         104   Arjun   23   Male    MCA    Indore     91          96    Yes
4         105   Rohan   21   Male    BCA  Jabalpur     74          80     No

In [ ]:
ds.shape

(20, 9)

In [6]:
ds.info

<bound method DataFrame.info of     Student_ID    Name  Age  Gender Course      City  Marks  Attendance Placed
0          101   Aarav   21    Male    MCA    Indore     78          82     No
1          102  Vivaan   22    Male    MCA    Bhopal     85          91    Yes
2          103  Aditya   20    Male    BCA     Satna     67          75     No
3          104   Arjun   23    Male    MCA    Indore     91          96    Yes
4          105   Rohan   21    Male    BCA  Jabalpur     74          80     No
5          106   Kabir   22    Male    MCA    Bhopal     88          88    Yes
6          107   Rahul   24    Male    BCA    Indore     62          70     No
7          108   Karan   20    Male    MCA     Satna     95          98    Yes
8          109   Ankit   23    Male    BCA  Jabalpur     71          77     No
9          110   Sahil   21    Male    MCA    Indore     83          85    Yes
10         111    Neha   22  Female    MCA    Bhopal     89          93    Yes
11         112   Priya   20  Female    BCA    Indore     76          81     No
12         113  Ananya   21  Female    MCA     Satna     92          95    Yes
13         114    Isha   23  Female    BCA  Jabalpur     68          72     No
14         115   Sneha   22  Female    MCA    Indore     81          87    Yes
15         116   Pooja   24  Female    BCA    Bhopal     73          79     No
16         117    Riya   21  Female    MCA     Satna     87          90    Yes
17         118   Kavya   20  Female    BCA    Indore     64          69     No
18         119  Simran   23  Female    MCA  Jabalpur     90          94    Yes
19         120   Aditi   22  Female    BCA    Bhopal     79          84     No>

In [7]:
ds.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Course', 'City', 'Marks',
       'Attendance', 'Placed'],
      dtype='object')

In [8]:
ds.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Course        0
City          0
Marks         0
Attendance    0
Placed        0
dtype: int64