<a href="https://colab.research.google.com/github/rajmishra-dev/python-project/blob/main/Pandas_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data Analysis Roadmap

We will use this **50-row CSV dataset** to learn and practice important Pandas operations step by step, following a **Basic → Intermediate → Advanced** approach.

## Topics We Will Cover

1. Pandas Introduction and DataFrame
2. Reading CSV Files
3. `head()`, `tail()`, `shape`, `columns`, and `index`
4. `info()` and `describe()`
5. Selecting Columns and Rows
6. `loc[]` and `iloc[]`
7. Filtering Data
8. Adding, Updating, and Deleting Columns
9. Sorting Data
10. Handling Missing Values
11. Handling Duplicate Data
12. `apply()`, `map()`, and `lambda`
13. `groupby()`
14. Aggregation
15. `merge()`, `join()`, and `concat()`
16. `pivot_table()`
17. String Operations
18. Date and Time Operations
19. Encoding and Categorical Data
20. Data Cleaning for Machine Learning
21. Feature Engineering
22. Advanced Pandas and ML Preprocessing

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pandas_practice_50rows.csv to pandas_practice_50rows.csv

In [ ]:
import pandas as pd
df = pd.read_csv("pandas_practice_50rows.csv")
print(df)

    ID     Name  Age       City  Marks
0    1       Om   18     Jaipur     63
1    2    Rohan   23  Bangalore     64
2    3     Pari   20  Bangalore     66
3    4    Kunal   25    Chennai     50
4    5    Kabir   18     Jaipur     51
5    6     Pari   19    Chennai     94
6    7    Rishi   24       Pune     84
7    8    Kunal   20    Chennai     77
8    9    Anika   29     Mumbai     70
9   10    Rahul   18     Jaipur     56
10  11    Kunal   21     Jaipur     58
11  12   Nikhil   19    Kolkata     77
12  13    Kabir   19     Jaipur     67
13  14   Sameer   25      Delhi     51
14  15    Kunal   30      Delhi     54
15  16    Manav   20    Kolkata     72
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
18  19    Kunal   20  Bangalore     75
19  20  Lavanya   18  Bangalore     66
20  21     Mira   28  Bangalore     99
21  22    Kabir   28       Pune     81
22  23    Rehan   19       Pune    100
23  24    Naina   29  Bangalore     76
24  25    Sanya   20    Chennai     88
25  26    Meera   20      Delhi     84
26  27    Arjun   22      Delhi    100
27  28    Sneha   23  Bangalore     91
28  29    Kunal   26     Mumbai     57
29  30     Aman   24    Chennai     85
30  31   Vikram   18  Bangalore     99
31  32   Simran   29     Jaipur     80
32  33     Alia   28      Delhi     55
33  34     Aman   27  Hyderabad     89
34  35    Sanya   24     Jaipur     70
35  36    Arjun   19       Pune     99
36  37    Kabir   22    Kolkata     69
37  38     Alia   18     Jaipur     60
38  39    Rohan   23      Delhi     83
39  40    Kabir   22      Delhi     58
40  41    Arjun   21     Jaipur    100
41  42     Riya   27     Jaipur     88
42  43   Nikhil   21       Pune     98
43  44    Kaira   29     Jaipur     87
44  45   Sameer   23     Jaipur     50
45  46   Sameer   19     Jaipur     85
46  47     Sara   27    Kolkata     90
47  48   Sameer   28      Delhi     70
48  49   Ritesh   28     Mumbai     59
49  50     Sara   19  Hyderabad     92

 #1 The " head()" function print first  5 row  Defaultly..!

In [ ]:
print(df.head())

   ID   Name  Age       City  Marks
0   1     Om   18     Jaipur     63
1   2  Rohan   23  Bangalore     64
2   3   Pari   20  Bangalore     66
3   4  Kunal   25    Chennai     50
4   5  Kabir   18     Jaipur     51

In [ ]:
print(df.head(10)) #print 10 row, we use specific number..!

   ID   Name  Age       City  Marks
0   1     Om   18     Jaipur     63
1   2  Rohan   23  Bangalore     64
2   3   Pari   20  Bangalore     66
3   4  Kunal   25    Chennai     50
4   5  Kabir   18     Jaipur     51
5   6   Pari   19    Chennai     94
6   7  Rishi   24       Pune     84
7   8  Kunal   20    Chennai     77
8   9  Anika   29     Mumbai     70
9  10  Rahul   18     Jaipur     56

In [ ]:
print(df.tail()) # lowest row

    ID    Name  Age       City  Marks
45  46  Sameer   19     Jaipur     85
46  47    Sara   27    Kolkata     90
47  48  Sameer   28      Delhi     70
48  49  Ritesh   28     Mumbai     59
49  50    Sara   19  Hyderabad     92

In [ ]:
print(df.tail(10)) # loewest 10 line

    ID    Name  Age       City  Marks
40  41   Arjun   21     Jaipur    100
41  42    Riya   27     Jaipur     88
42  43  Nikhil   21       Pune     98
43  44   Kaira   29     Jaipur     87
44  45  Sameer   23     Jaipur     50
45  46  Sameer   19     Jaipur     85
46  47    Sara   27    Kolkata     90
47  48  Sameer   28      Delhi     70
48  49  Ritesh   28     Mumbai     59
49  50    Sara   19  Hyderabad     92

In [ ]:
print(df.shape)#size of table colum or row

(50, 5)

In [ ]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [ ]:
print(df.columns.tolist()) # list format the

['ID', 'Name', 'Age', 'City', 'Marks']

In [ ]:
print(df.dtypes)

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

# Print the Dataset overall information..!

In [ ]:
df.info

<bound method DataFrame.info of     ID     Name  Age       City  Marks
0    1       Om   18     Jaipur     63
1    2    Rohan   23  Bangalore     64
2    3     Pari   20  Bangalore     66
3    4    Kunal   25    Chennai     50
4    5    Kabir   18     Jaipur     51
5    6     Pari   19    Chennai     94
6    7    Rishi   24       Pune     84
7    8    Kunal   20    Chennai     77
8    9    Anika   29     Mumbai     70
9   10    Rahul   18     Jaipur     56
10  11    Kunal   21     Jaipur     58
11  12   Nikhil   19    Kolkata     77
12  13    Kabir   19     Jaipur     67
13  14   Sameer   25      Delhi     51
14  15    Kunal   30      Delhi     54
15  16    Manav   20    Kolkata     72
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
18  19    Kunal   20  Bangalore     75
19  20  Lavanya   18  Bangalore     66
20  21     Mira   28  Bangalore     99
21  22    Kabir   28       Pune     81
22  23    Rehan   19       Pune    100
23  24    Naina   29  Bangalore     76
24  25    Sanya   20    Chennai     88
25  26    Meera   20      Delhi     84
26  27    Arjun   22      Delhi    100
27  28    Sneha   23  Bangalore     91
28  29    Kunal   26     Mumbai     57
29  30     Aman   24    Chennai     85
30  31   Vikram   18  Bangalore     99
31  32   Simran   29     Jaipur     80
32  33     Alia   28      Delhi     55
33  34     Aman   27  Hyderabad     89
34  35    Sanya   24     Jaipur     70
35  36    Arjun   19       Pune     99
36  37    Kabir   22    Kolkata     69
37  38     Alia   18     Jaipur     60
38  39    Rohan   23      Delhi     83
39  40    Kabir   22      Delhi     58
40  41    Arjun   21     Jaipur    100
41  42     Riya   27     Jaipur     88
42  43   Nikhil   21       Pune     98
43  44    Kaira   29     Jaipur     87
44  45   Sameer   23     Jaipur     50
45  46   Sameer   19     Jaipur     85
46  47     Sara   27    Kolkata     90
47  48   Sameer   28      Delhi     70
48  49   Ritesh   28     Mumbai     59
49  50     Sara   19  Hyderabad     92>

In [ ]:
print(df.describe())

             ID        Age       Marks
count  50.00000  50.000000   50.000000
mean   25.50000  22.980000   75.660000
std    14.57738   3.872931   15.668257
min     1.00000  18.000000   50.000000
25%    13.25000  19.250000   63.250000
50%    25.50000  22.500000   75.500000
75%    37.75000  26.750000   88.000000
max    50.00000  30.000000  100.000000

In [ ]:
print(df["Age"].describe())

count    50.000000
mean     22.980000
std       3.872931
min      18.000000
25%      19.250000
50%      22.500000
75%      26.750000
max      30.000000
Name: Age, dtype: float64

# NOw, we are Selecting single columns..!

In [ ]:
df["Age"]# it contain index and there Data

0     18
1     23
2     20
3     25
4     18
5     19
6     24
7     20
8     29
9     18
10    21
11    19
12    19
13    25
14    30
15    20
16    26
17    26
18    20
19    18
20    28
21    28
22    19
23    29
24    20
25    20
26    22
27    23
28    26
29    24
30    18
31    29
32    28
33    27
34    24
35    19
36    22
37    18
38    23
39    22
40    21
41    27
42    21
43    29
44    23
45    19
46    27
47    28
48    28
49    19
Name: Age, dtype: int64

In [ ]:
df[["Name","Age","Marks"]]# multiple columns data print..!

       Name  Age  Marks
0        Om   18     63
1     Rohan   23     64
2      Pari   20     66
3     Kunal   25     50
4     Kabir   18     51
5      Pari   19     94
6     Rishi   24     84
7     Kunal   20     77
8     Anika   29     70
9     Rahul   18     56
10    Kunal   21     58
11   Nikhil   19     77
12    Kabir   19     67
13   Sameer   25     51
14    Kunal   30     54
15    Manav   20     72
16  Lavanya   26     71
17    Kaira   26     75
18    Kunal   20     75
19  Lavanya   18     66
20     Mira   28     99
21    Kabir   28     81
22    Rehan   19    100
23    Naina   29     76
24    Sanya   20     88
25    Meera   20     84
26    Arjun   22    100
27    Sneha   23     91
28    Kunal   26     57
29     Aman   24     85
30   Vikram   18     99
31   Simran   29     80
32     Alia   28     55
33     Aman   27     89
34    Sanya   24     70
35    Arjun   19     99
36    Kabir   22     69
37     Alia   18     60
38    Rohan   23     83
39    Kabir   22     58
40    Arjun   21    100
41     Riya   27     88
42   Nikhil   21     98
43    Kaira   29     87
44   Sameer   23     50
45   Sameer   19     85
46     Sara   27     90
47   Sameer   28     70
48   Ritesh   28     59
49     Sara   19     92

# Selecting a numerical feature..!

In [ ]:
x = df[["Age"]]
print(x)

    Age
0    18
1    23
2    20
3    25
4    18
5    19
6    24
7    20
8    29
9    18
10   21
11   19
12   19
13   25
14   30
15   20
16   26
17   26
18   20
19   18
20   28
21   28
22   19
23   29
24   20
25   20
26   22
27   23
28   26
29   24
30   18
31   29
32   28
33   27
34   24
35   19
36   22
37   18
38   23
39   22
40   21
41   27
42   21
43   29
44   23
45   19
46   27
47   28
48   28
49   19

#Selecting a Traget

In [ ]:
y = df[["Marks"]]

#Selecting a Rows

In [ ]:
df.iloc[0] # first Row Selected..!

ID            1
Name         Om
Age          18
City     Jaipur
Marks        63
Name: 0, dtype: object

In [ ]:
df.iloc[1] # first rows selected..!

ID               2
Name         Rohan
Age             23
City     Bangalore
Marks           64
Name: 1, dtype: object

In [ ]:
print(df["Name"])

print(df[["Name", "City"]])

print(df.iloc[0])

print(df.iloc[0:5])

print(df.iloc[10:20])

0          Om
1       Rohan
2        Pari
3       Kunal
4       Kabir
5        Pari
6       Rishi
7       Kunal
8       Anika
9       Rahul
10      Kunal
11     Nikhil
12      Kabir
13     Sameer
14      Kunal
15      Manav
16    Lavanya
17      Kaira
18      Kunal
19    Lavanya
20       Mira
21      Kabir
22      Rehan
23      Naina
24      Sanya
25      Meera
26      Arjun
27      Sneha
28      Kunal
29       Aman
30     Vikram
31     Simran
32       Alia
33       Aman
34      Sanya
35      Arjun
36      Kabir
37       Alia
38      Rohan
39      Kabir
40      Arjun
41       Riya
42     Nikhil
43      Kaira
44     Sameer
45     Sameer
46       Sara
47     Sameer
48     Ritesh
49       Sara
Name: Name, dtype: object
       Name       City
0        Om     Jaipur
1     Rohan  Bangalore
2      Pari  Bangalore
3     Kunal    Chennai
4     Kabir     Jaipur
5      Pari    Chennai
6     Rishi       Pune
7     Kunal    Chennai
8     Anika     Mumbai
9     Rahul     Jaipur
10    Kunal     Jaipur
11   Nikhil    Kolkata
12    Kabir     Jaipur
13   Sameer      Delhi
14    Kunal      Delhi
15    Manav    Kolkata
16  Lavanya  Bangalore
17    Kaira  Hyderabad
18    Kunal  Bangalore
19  Lavanya  Bangalore
20     Mira  Bangalore
21    Kabir       Pune
22    Rehan       Pune
23    Naina  Bangalore
24    Sanya    Chennai
25    Meera      Delhi
26    Arjun      Delhi
27    Sneha  Bangalore
28    Kunal     Mumbai
29     Aman    Chennai
30   Vikram  Bangalore
31   Simran     Jaipur
32     Alia      Delhi
33     Aman  Hyderabad
34    Sanya     Jaipur
35    Arjun       Pune
36    Kabir    Kolkata
37     Alia     Jaipur
38    Rohan      Delhi
39    Kabir      Delhi
40    Arjun     Jaipur
41     Riya     Jaipur
42   Nikhil       Pune
43    Kaira     Jaipur
44   Sameer     Jaipur
45   Sameer     Jaipur
46     Sara    Kolkata
47   Sameer      Delhi
48   Ritesh     Mumbai
49     Sara  Hyderabad
ID            1
Name         Om
Age          18
City     Jaipur
Marks        63
Name: 0, dtype: object
   ID   Name  Age       City  Marks
0   1     Om   18     Jaipur     63
1   2  Rohan   23  Bangalore     64
2   3   Pari   20  Bangalore     66
3   4  Kunal   25    Chennai     50
4   5  Kabir   18     Jaipur     51
    ID     Name  Age       City  Marks
10  11    Kunal   21     Jaipur     58
11  12   Nikhil   19    Kolkata     77
12  13    Kabir   19     Jaipur     67
13  14   Sameer   25      Delhi     51
14  15    Kunal   30      Delhi     54
15  16    Manav   20    Kolkata     72
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
18  19    Kunal   20  Bangalore     75
19  20  Lavanya   18  Bangalore     66

In [ ]:
df.loc[0]

ID            1
Name         Om
Age          18
City     Jaipur
Marks        63
Name: 0, dtype: object

In [ ]:
df.loc[0:4, ["Name", "Age", "City"]]

    Name  Age       City
0     Om   18     Jaipur
1  Rohan   23  Bangalore
2   Pari   20  Bangalore
3  Kunal   25    Chennai
4  Kabir   18     Jaipur

In [ ]:
print("The Age greter the 25..!")
df[df["Age"] > 25]

The Age greter the 25..!

    ID     Name  Age       City  Marks
8    9    Anika   29     Mumbai     70
14  15    Kunal   30      Delhi     54
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
20  21     Mira   28  Bangalore     99
21  22    Kabir   28       Pune     81
23  24    Naina   29  Bangalore     76
28  29    Kunal   26     Mumbai     57
31  32   Simran   29     Jaipur     80
32  33     Alia   28      Delhi     55
33  34     Aman   27  Hyderabad     89
41  42     Riya   27     Jaipur     88
43  44    Kaira   29     Jaipur     87
46  47     Sara   27    Kolkata     90
47  48   Sameer   28      Delhi     70
48  49   Ritesh   28     Mumbai     59

In [ ]:
print("Marks greater than 80..!")
df[df["Marks"] > 80]

Marks greater than 80..!

    ID    Name  Age       City  Marks
5    6    Pari   19    Chennai     94
6    7   Rishi   24       Pune     84
20  21    Mira   28  Bangalore     99
21  22   Kabir   28       Pune     81
22  23   Rehan   19       Pune    100
24  25   Sanya   20    Chennai     88
25  26   Meera   20      Delhi     84
26  27   Arjun   22      Delhi    100
27  28   Sneha   23  Bangalore     91
29  30    Aman   24    Chennai     85
30  31  Vikram   18  Bangalore     99
33  34    Aman   27  Hyderabad     89
35  36   Arjun   19       Pune     99
38  39   Rohan   23      Delhi     83
40  41   Arjun   21     Jaipur    100
41  42    Riya   27     Jaipur     88
42  43  Nikhil   21       Pune     98
43  44   Kaira   29     Jaipur     87
45  46  Sameer   19     Jaipur     85
46  47    Sara   27    Kolkata     90
49  50    Sara   19  Hyderabad     92

In [ ]:
print("print a Age of equel 25 ")
df[df["Age"] == 25]

print a Age of equel 25

    ID    Name  Age     City  Marks
3    4   Kunal   25  Chennai     50
13  14  Sameer   25    Delhi     51

In [ ]:
print("print a marks of less than 50..!")
df[df["Marks"] < 50]

print a marks of less than 50..!

Empty DataFrame
Columns: [ID, Name, Age, City, Marks]
Index: []

In [ ]:
print("use multiple conditions..!")
df[(df["Age"] > 25) & (df["Marks"] > 70)]

use multiple conditions..!

    ID     Name  Age       City  Marks
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
20  21     Mira   28  Bangalore     99
21  22    Kabir   28       Pune     81
23  24    Naina   29  Bangalore     76
31  32   Simran   29     Jaipur     80
33  34     Aman   27  Hyderabad     89
41  42     Riya   27     Jaipur     88
43  44    Kaira   29     Jaipur     87
46  47     Sara   27    Kolkata     90

In [ ]:
print("Print a filter + select columns..!")
df.loc[df["Marks"] > 80 ,["Name","Age","Marks"]]

Print a filter + select columns..!

      Name  Age  Marks
5     Pari   19     94
6    Rishi   24     84
20    Mira   28     99
21   Kabir   28     81
22   Rehan   19    100
24   Sanya   20     88
25   Meera   20     84
26   Arjun   22    100
27   Sneha   23     91
29    Aman   24     85
30  Vikram   18     99
33    Aman   27     89
35   Arjun   19     99
38   Rohan   23     83
40   Arjun   21    100
41    Riya   27     88
42  Nikhil   21     98
43   Kaira   29     87
45  Sameer   19     85
46    Sara   27     90
49    Sara   19     92

#Practies for this Topices..!

In [ ]:
print("A Age Grater then 25..!")
df[df["Age"] > 25]

print("Marks grater than 80")
df[df["Marks"] > 80]


print("print then a less both Age and Marks..!")
df[df["Age"] < 25]
df[df["Marks"] < 50 ]

print("Multiple condition in one line")
df[(df["Age"] == 25) & (df["Marks"] == 80)]

A Age Grater then 25..!
Marks grater than 80
print then a less both Age and Marks..!
Multiple condition in one line

Empty DataFrame
Columns: [ID, Name, Age, City, Marks]
Index: []

#Advanced Filtering

In [ ]:
df[df["City"].isin(["Pune", "Delhi"])]

    ID    Name  Age   City  Marks
6    7   Rishi   24   Pune     84
13  14  Sameer   25  Delhi     51
14  15   Kunal   30  Delhi     54
21  22   Kabir   28   Pune     81
22  23   Rehan   19   Pune    100
25  26   Meera   20  Delhi     84
26  27   Arjun   22  Delhi    100
32  33    Alia   28  Delhi     55
35  36   Arjun   19   Pune     99
38  39   Rohan   23  Delhi     83
39  40   Kabir   22  Delhi     58
42  43  Nikhil   21   Pune     98
47  48  Sameer   28  Delhi     70

In [ ]:
print("find the value in range..!")
df[df["Age"].between(25,30)]

df[df["Marks"].between(60,80)]

find the value in range..!

    ID     Name  Age       City  Marks
0    1       Om   18     Jaipur     63
1    2    Rohan   23  Bangalore     64
2    3     Pari   20  Bangalore     66
7    8    Kunal   20    Chennai     77
8    9    Anika   29     Mumbai     70
11  12   Nikhil   19    Kolkata     77
12  13    Kabir   19     Jaipur     67
15  16    Manav   20    Kolkata     72
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
18  19    Kunal   20  Bangalore     75
19  20  Lavanya   18  Bangalore     66
23  24    Naina   29  Bangalore     76
31  32   Simran   29     Jaipur     80
34  35    Sanya   24     Jaipur     70
36  37    Kabir   22    Kolkata     69
37  38     Alia   18     Jaipur     60
47  48   Sameer   28      Delhi     70

#Query()
##is used to filter rows from a DataFrame using a readable condition/expression.

In [ ]:
df.query("Age >20 and Marks >80")

    ID    Name  Age       City  Marks
6    7   Rishi   24       Pune     84
20  21    Mira   28  Bangalore     99
21  22   Kabir   28       Pune     81
26  27   Arjun   22      Delhi    100
27  28   Sneha   23  Bangalore     91
29  30    Aman   24    Chennai     85
33  34    Aman   27  Hyderabad     89
38  39   Rohan   23      Delhi     83
40  41   Arjun   21     Jaipur    100
41  42    Riya   27     Jaipur     88
42  43  Nikhil   21       Pune     98
43  44   Kaira   29     Jaipur     87
46  47    Sara   27    Kolkata     90

In [ ]:
df.query("Age > 25 or Marks > 70")

    ID     Name  Age       City  Marks
5    6     Pari   19    Chennai     94
6    7    Rishi   24       Pune     84
7    8    Kunal   20    Chennai     77
8    9    Anika   29     Mumbai     70
11  12   Nikhil   19    Kolkata     77
14  15    Kunal   30      Delhi     54
15  16    Manav   20    Kolkata     72
16  17  Lavanya   26  Bangalore     71
17  18    Kaira   26  Hyderabad     75
18  19    Kunal   20  Bangalore     75
20  21     Mira   28  Bangalore     99
21  22    Kabir   28       Pune     81
22  23    Rehan   19       Pune    100
23  24    Naina   29  Bangalore     76
24  25    Sanya   20    Chennai     88
25  26    Meera   20      Delhi     84
26  27    Arjun   22      Delhi    100
27  28    Sneha   23  Bangalore     91
28  29    Kunal   26     Mumbai     57
29  30     Aman   24    Chennai     85
30  31   Vikram   18  Bangalore     99
31  32   Simran   29     Jaipur     80
32  33     Alia   28      Delhi     55
33  34     Aman   27  Hyderabad     89
35  36    Arjun   19       Pune     99
38  39    Rohan   23      Delhi     83
40  41    Arjun   21     Jaipur    100
41  42     Riya   27     Jaipur     88
42  43   Nikhil   21       Pune     98
43  44    Kaira   29     Jaipur     87
45  46   Sameer   19     Jaipur     85
46  47     Sara   27    Kolkata     90
47  48   Sameer   28      Delhi     70
48  49   Ritesh   28     Mumbai     59
49  50     Sara   19  Hyderabad     92

#not
##condition is used to select rows where a given condition is NOT true.

In [ ]:
df.query("not(Age >22)")

    ID     Name  Age       City  Marks
0    1       Om   18     Jaipur     63
2    3     Pari   20  Bangalore     66
4    5    Kabir   18     Jaipur     51
5    6     Pari   19    Chennai     94
7    8    Kunal   20    Chennai     77
9   10    Rahul   18     Jaipur     56
10  11    Kunal   21     Jaipur     58
11  12   Nikhil   19    Kolkata     77
12  13    Kabir   19     Jaipur     67
15  16    Manav   20    Kolkata     72
18  19    Kunal   20  Bangalore     75
19  20  Lavanya   18  Bangalore     66
22  23    Rehan   19       Pune    100
24  25    Sanya   20    Chennai     88
25  26    Meera   20      Delhi     84
26  27    Arjun   22      Delhi    100
30  31   Vikram   18  Bangalore     99
35  36    Arjun   19       Pune     99
36  37    Kabir   22    Kolkata     69
37  38     Alia   18     Jaipur     60
39  40    Kabir   22      Delhi     58
40  41    Arjun   21     Jaipur    100
42  43   Nikhil   21       Pune     98
45  46   Sameer   19     Jaipur     85
49  50     Sara   19  Hyderabad     92

Adding, Updating & Deleting Columns

In [ ]:
# 1. Add a new column
# Why: Existing data se ek new feature create karne ke liye
df["Passed"] =df ["Marks"] >=40

print("\nAfter adding Passed column:")
print(df)

After adding Passed column:
    ID     Name  Age       City  Marks  Passed
0    1       Om   18     Jaipur     63    True
1    2    Rohan   23  Bangalore     64    True
2    3     Pari   20  Bangalore     66    True
3    4    Kunal   25    Chennai     50    True
4    5    Kabir   18     Jaipur     51    True
5    6     Pari   19    Chennai     94    True
6    7    Rishi   24       Pune     84    True
7    8    Kunal   20    Chennai     77    True
8    9    Anika   29     Mumbai     70    True
9   10    Rahul   18     Jaipur     56    True
10  11    Kunal   21     Jaipur     58    True
11  12   Nikhil   19    Kolkata     77    True
12  13    Kabir   19     Jaipur     67    True
13  14   Sameer   25      Delhi     51    True
14  15    Kunal   30      Delhi     54    True
15  16    Manav   20    Kolkata     72    True
16  17  Lavanya   26  Bangalore     71    True
17  18    Kaira   26  Hyderabad     75    True
18  19    Kunal   20  Bangalore     75    True
19  20  Lavanya   18  Bangalore     66    True
20  21     Mira   28  Bangalore     99    True
21  22    Kabir   28       Pune     81    True
22  23    Rehan   19       Pune    100    True
23  24    Naina   29  Bangalore     76    True
24  25    Sanya   20    Chennai     88    True
25  26    Meera   20      Delhi     84    True
26  27    Arjun   22      Delhi    100    True
27  28    Sneha   23  Bangalore     91    True
28  29    Kunal   26     Mumbai     57    True
29  30     Aman   24    Chennai     85    True
30  31   Vikram   18  Bangalore     99    True
31  32   Simran   29     Jaipur     80    True
32  33     Alia   28      Delhi     55    True
33  34     Aman   27  Hyderabad     89    True
34  35    Sanya   24     Jaipur     70    True
35  36    Arjun   19       Pune     99    True
36  37    Kabir   22    Kolkata     69    True
37  38     Alia   18     Jaipur     60    True
38  39    Rohan   23      Delhi     83    True
39  40    Kabir   22      Delhi     58    True
40  41    Arjun   21     Jaipur    100    True
41  42     Riya   27     Jaipur     88    True
42  43   Nikhil   21       Pune     98    True
43  44    Kaira   29     Jaipur     87    True
44  45   Sameer   23     Jaipur     50    True
45  46   Sameer   19     Jaipur     85    True
46  47     Sara   27    Kolkata     90    True
47  48   Sameer   28      Delhi     70    True
48  49   Ritesh   28     Mumbai     59    True
49  50     Sara   19  Hyderabad     92    True

# 2. Add a calculated column
# Why: Existing numerical data se new calculated feature banane ke liye

In [ ]:
df["Marks_Double"] = df["Marks"] * 2

print("After adding a Marks_Double column:")
print(df)

After adding a Marks_Double column:
    ID     Name  Age       City  Marks  Passed  Marks_Double
0    1       Om   18     Jaipur     63    True           126
1    2    Rohan   23  Bangalore     64    True           128
2    3     Pari   20  Bangalore     66    True           132
3    4    Kunal   25    Chennai     50    True           100
4    5    Kabir   18     Jaipur     51    True           102
5    6     Pari   19    Chennai     94    True           188
6    7    Rishi   24       Pune     84    True           168
7    8    Kunal   20    Chennai     77    True           154
8    9    Anika   29     Mumbai     70    True           140
9   10    Rahul   18     Jaipur     56    True           112
10  11    Kunal   21     Jaipur     58    True           116
11  12   Nikhil   19    Kolkata     77    True           154
12  13    Kabir   19     Jaipur     67    True           134
13  14   Sameer   25      Delhi     51    True           102
14  15    Kunal   30      Delhi     54    True           108
15  16    Manav   20    Kolkata     72    True           144
16  17  Lavanya   26  Bangalore     71    True           142
17  18    Kaira   26  Hyderabad     75    True           150
18  19    Kunal   20  Bangalore     75    True           150
19  20  Lavanya   18  Bangalore     66    True           132
20  21     Mira   28  Bangalore     99    True           198
21  22    Kabir   28       Pune     81    True           162
22  23    Rehan   19       Pune    100    True           200
23  24    Naina   29  Bangalore     76    True           152
24  25    Sanya   20    Chennai     88    True           176
25  26    Meera   20      Delhi     84    True           168
26  27    Arjun   22      Delhi    100    True           200
27  28    Sneha   23  Bangalore     91    True           182
28  29    Kunal   26     Mumbai     57    True           114
29  30     Aman   24    Chennai     85    True           170
30  31   Vikram   18  Bangalore     99    True           198
31  32   Simran   29     Jaipur     80    True           160
32  33     Alia   28      Delhi     55    True           110
33  34     Aman   27  Hyderabad     89    True           178
34  35    Sanya   24     Jaipur     70    True           140
35  36    Arjun   19       Pune     99    True           198
36  37    Kabir   22    Kolkata     69    True           138
37  38     Alia   18     Jaipur     60    True           120
38  39    Rohan   23      Delhi     83    True           166
39  40    Kabir   22      Delhi     58    True           116
40  41    Arjun   21     Jaipur    100    True           200
41  42     Riya   27     Jaipur     88    True           176
42  43   Nikhil   21       Pune     98    True           196
43  44    Kaira   29     Jaipur     87    True           174
44  45   Sameer   23     Jaipur     50    True           100
45  46   Sameer   19     Jaipur     85    True           170
46  47     Sara   27    Kolkata     90    True           180
47  48   Sameer   28      Delhi     70    True           140
48  49   Ritesh   28     Mumbai     59    True           118
49  50     Sara   19  Hyderabad     92    True           184

# 3. Add another calculated column
# Why: Future value calculate karke new feature banane ke liye

In [ ]:
df["Age_Next_Year"] = df["Age"] + 1

print("\n after adding a Age_Next_yera column:\n")
print(df)

 after adding a Age_Next_yera column:

    ID     Name  Age       City  Marks  Passed  Marks_Double  Age_Next_Year
0    1       Om   18     Jaipur     63    True           126             19
1    2    Rohan   23  Bangalore     64    True           128             24
2    3     Pari   20  Bangalore     66    True           132             21
3    4    Kunal   25    Chennai     50    True           100             26
4    5    Kabir   18     Jaipur     51    True           102             19
5    6     Pari   19    Chennai     94    True           188             20
6    7    Rishi   24       Pune     84    True           168             25
7    8    Kunal   20    Chennai     77    True           154             21
8    9    Anika   29     Mumbai     70    True           140             30
9   10    Rahul   18     Jaipur     56    True           112             19
10  11    Kunal   21     Jaipur     58    True           116             22
11  12   Nikhil   19    Kolkata     77    True           154             20
12  13    Kabir   19     Jaipur     67    True           134             20
13  14   Sameer   25      Delhi     51    True           102             26
14  15    Kunal   30      Delhi     54    True           108             31
15  16    Manav   20    Kolkata     72    True           144             21
16  17  Lavanya   26  Bangalore     71    True           142             27
17  18    Kaira   26  Hyderabad     75    True           150             27
18  19    Kunal   20  Bangalore     75    True           150             21
19  20  Lavanya   18  Bangalore     66    True           132             19
20  21     Mira   28  Bangalore     99    True           198             29
21  22    Kabir   28       Pune     81    True           162             29
22  23    Rehan   19       Pune    100    True           200             20
23  24    Naina   29  Bangalore     76    True           152             30
24  25    Sanya   20    Chennai     88    True           176             21
25  26    Meera   20      Delhi     84    True           168             21
26  27    Arjun   22      Delhi    100    True           200             23
27  28    Sneha   23  Bangalore     91    True           182             24
28  29    Kunal   26     Mumbai     57    True           114             27
29  30     Aman   24    Chennai     85    True           170             25
30  31   Vikram   18  Bangalore     99    True           198             19
31  32   Simran   29     Jaipur     80    True           160             30
32  33     Alia   28      Delhi     55    True           110             29
33  34     Aman   27  Hyderabad     89    True           178             28
34  35    Sanya   24     Jaipur     70    True           140             25
35  36    Arjun   19       Pune     99    True           198             20
36  37    Kabir   22    Kolkata     69    True           138             23
37  38     Alia   18     Jaipur     60    True           120             19
38  39    Rohan   23      Delhi     83    True           166             24
39  40    Kabir   22      Delhi     58    True           116             23
40  41    Arjun   21     Jaipur    100    True           200             22
41  42     Riya   27     Jaipur     88    True           176             28
42  43   Nikhil   21       Pune     98    True           196             22
43  44    Kaira   29     Jaipur     87    True           174             30
44  45   Sameer   23     Jaipur     50    True           100             24
45  46   Sameer   19     Jaipur     85    True           170             20
46  47     Sara   27    Kolkata     90    True           180             28
47  48   Sameer   28      Delhi     70    True           140             29
48  49   Ritesh   28     Mumbai     59    True           118             29
49  50     Sara   19  Hyderabad     92    True           184             20

# 4. Conditional update
### Why: Condition ke basis par specific values modify karne ke liye

In [ ]:
df.loc[df["Marks"] < 40, "Marks"] = 40

print("\nAfter updating Marks below 40:")
print(df)

After updating Marks below 40:
    ID     Name  Age       City  Marks  Passed  Marks_Double  Age_Next_Year
0    1       Om   18     Jaipur     63    True           126             19
1    2    Rohan   23  Bangalore     64    True           128             24
2    3     Pari   20  Bangalore     66    True           132             21
3    4    Kunal   25    Chennai     50    True           100             26
4    5    Kabir   18     Jaipur     51    True           102             19
5    6     Pari   19    Chennai     94    True           188             20
6    7    Rishi   24       Pune     84    True           168             25
7    8    Kunal   20    Chennai     77    True           154             21
8    9    Anika   29     Mumbai     70    True           140             30
9   10    Rahul   18     Jaipur     56    True           112             19
10  11    Kunal   21     Jaipur     58    True           116             22
11  12   Nikhil   19    Kolkata     77    True           154             20
12  13    Kabir   19     Jaipur     67    True           134             20
13  14   Sameer   25      Delhi     51    True           102             26
14  15    Kunal   30      Delhi     54    True           108             31
15  16    Manav   20    Kolkata     72    True           144             21
16  17  Lavanya   26  Bangalore     71    True           142             27
17  18    Kaira   26  Hyderabad     75    True           150             27
18  19    Kunal   20  Bangalore     75    True           150             21
19  20  Lavanya   18  Bangalore     66    True           132             19
20  21     Mira   28  Bangalore     99    True           198             29
21  22    Kabir   28       Pune     81    True           162             29
22  23    Rehan   19       Pune    100    True           200             20
23  24    Naina   29  Bangalore     76    True           152             30
24  25    Sanya   20    Chennai     88    True           176             21
25  26    Meera   20      Delhi     84    True           168             21
26  27    Arjun   22      Delhi    100    True           200             23
27  28    Sneha   23  Bangalore     91    True           182             24
28  29    Kunal   26     Mumbai     57    True           114             27
29  30     Aman   24    Chennai     85    True           170             25
30  31   Vikram   18  Bangalore     99    True           198             19
31  32   Simran   29     Jaipur     80    True           160             30
32  33     Alia   28      Delhi     55    True           110             29
33  34     Aman   27  Hyderabad     89    True           178             28
34  35    Sanya   24     Jaipur     70    True           140             25
35  36    Arjun   19       Pune     99    True           198             20
36  37    Kabir   22    Kolkata     69    True           138             23
37  38     Alia   18     Jaipur     60    True           120             19
38  39    Rohan   23      Delhi     83    True           166             24
39  40    Kabir   22      Delhi     58    True           116             23
40  41    Arjun   21     Jaipur    100    True           200             22
41  42     Riya   27     Jaipur     88    True           176             28
42  43   Nikhil   21       Pune     98    True           196             22
43  44    Kaira   29     Jaipur     87    True           174             30
44  45   Sameer   23     Jaipur     50    True           100             24
45  46   Sameer   19     Jaipur     85    True           170             20
46  47     Sara   27    Kolkata     90    True           180             28
47  48   Sameer   28      Delhi     70    True           140             29
48  49   Ritesh   28     Mumbai     59    True           118             29
49  50     Sara   19  Hyderabad     92    True           184             20

# 5. Delete one column
### Why: Unwanted column remove karne ke liye

In [ ]:
df.drop("Marks_Double", axis=1, inplace=True)

print("\nAfter deleting Marks_Double:")
print(df)

After deleting Marks_Double:
    ID     Name  Age       City  Marks  Passed  Age_Next_Year
0    1       Om   18     Jaipur     63    True             19
1    2    Rohan   23  Bangalore     64    True             24
2    3     Pari   20  Bangalore     66    True             21
3    4    Kunal   25    Chennai     50    True             26
4    5    Kabir   18     Jaipur     51    True             19
5    6     Pari   19    Chennai     94    True             20
6    7    Rishi   24       Pune     84    True             25
7    8    Kunal   20    Chennai     77    True             21
8    9    Anika   29     Mumbai     70    True             30
9   10    Rahul   18     Jaipur     56    True             19
10  11    Kunal   21     Jaipur     58    True             22
11  12   Nikhil   19    Kolkata     77    True             20
12  13    Kabir   19     Jaipur     67    True             20
13  14   Sameer   25      Delhi     51    True             26
14  15    Kunal   30      Delhi     54    True             31
15  16    Manav   20    Kolkata     72    True             21
16  17  Lavanya   26  Bangalore     71    True             27
17  18    Kaira   26  Hyderabad     75    True             27
18  19    Kunal   20  Bangalore     75    True             21
19  20  Lavanya   18  Bangalore     66    True             19
20  21     Mira   28  Bangalore     99    True             29
21  22    Kabir   28       Pune     81    True             29
22  23    Rehan   19       Pune    100    True             20
23  24    Naina   29  Bangalore     76    True             30
24  25    Sanya   20    Chennai     88    True             21
25  26    Meera   20      Delhi     84    True             21
26  27    Arjun   22      Delhi    100    True             23
27  28    Sneha   23  Bangalore     91    True             24
28  29    Kunal   26     Mumbai     57    True             27
29  30     Aman   24    Chennai     85    True             25
30  31   Vikram   18  Bangalore     99    True             19
31  32   Simran   29     Jaipur     80    True             30
32  33     Alia   28      Delhi     55    True             29
33  34     Aman   27  Hyderabad     89    True             28
34  35    Sanya   24     Jaipur     70    True             25
35  36    Arjun   19       Pune     99    True             20
36  37    Kabir   22    Kolkata     69    True             23
37  38     Alia   18     Jaipur     60    True             19
38  39    Rohan   23      Delhi     83    True             24
39  40    Kabir   22      Delhi     58    True             23
40  41    Arjun   21     Jaipur    100    True             22
41  42     Riya   27     Jaipur     88    True             28
42  43   Nikhil   21       Pune     98    True             22
43  44    Kaira   29     Jaipur     87    True             30
44  45   Sameer   23     Jaipur     50    True             24
45  46   Sameer   19     Jaipur     85    True             20
46  47     Sara   27    Kolkata     90    True             28
47  48   Sameer   28      Delhi     70    True             29
48  49   Ritesh   28     Mumbai     59    True             29
49  50     Sara   19  Hyderabad     92    True             20

# 6. Delete multiple columns
### Why: Ek saath multiple unwanted columns remove karne ke liye

In [ ]:
df.drop(["Age_Next_Year"], axis=1, inplace=True)

print("\nAfter deleting Age_Next_Year:")
print(df)

After deleting Age_Next_Year:
    ID     Name  Age       City  Marks  Passed
0    1       Om   18     Jaipur     63    True
1    2    Rohan   23  Bangalore     64    True
2    3     Pari   20  Bangalore     66    True
3    4    Kunal   25    Chennai     50    True
4    5    Kabir   18     Jaipur     51    True
5    6     Pari   19    Chennai     94    True
6    7    Rishi   24       Pune     84    True
7    8    Kunal   20    Chennai     77    True
8    9    Anika   29     Mumbai     70    True
9   10    Rahul   18     Jaipur     56    True
10  11    Kunal   21     Jaipur     58    True
11  12   Nikhil   19    Kolkata     77    True
12  13    Kabir   19     Jaipur     67    True
13  14   Sameer   25      Delhi     51    True
14  15    Kunal   30      Delhi     54    True
15  16    Manav   20    Kolkata     72    True
16  17  Lavanya   26  Bangalore     71    True
17  18    Kaira   26  Hyderabad     75    True
18  19    Kunal   20  Bangalore     75    True
19  20  Lavanya   18  Bangalore     66    True
20  21     Mira   28  Bangalore     99    True
21  22    Kabir   28       Pune     81    True
22  23    Rehan   19       Pune    100    True
23  24    Naina   29  Bangalore     76    True
24  25    Sanya   20    Chennai     88    True
25  26    Meera   20      Delhi     84    True
26  27    Arjun   22      Delhi    100    True
27  28    Sneha   23  Bangalore     91    True
28  29    Kunal   26     Mumbai     57    True
29  30     Aman   24    Chennai     85    True
30  31   Vikram   18  Bangalore     99    True
31  32   Simran   29     Jaipur     80    True
32  33     Alia   28      Delhi     55    True
33  34     Aman   27  Hyderabad     89    True
34  35    Sanya   24     Jaipur     70    True
35  36    Arjun   19       Pune     99    True
36  37    Kabir   22    Kolkata     69    True
37  38     Alia   18     Jaipur     60    True
38  39    Rohan   23      Delhi     83    True
39  40    Kabir   22      Delhi     58    True
40  41    Arjun   21     Jaipur    100    True
41  42     Riya   27     Jaipur     88    True
42  43   Nikhil   21       Pune     98    True
43  44    Kaira   29     Jaipur     87    True
44  45   Sameer   23     Jaipur     50    True
45  46   Sameer   19     Jaipur     85    True
46  47     Sara   27    Kolkata     90    True
47  48   Sameer   28      Delhi     70    True
48  49   Ritesh   28     Mumbai     59    True
49  50     Sara   19  Hyderabad     92    True

#Sorting Data

# 1. Sort by Marks in ascending order.

In [41]:
df_sorted_marks = df.sort_values("Marks")

print("\nMarks - Ascending Order:")
print(df_sorted_marks)

Marks - Ascending Order:
    ID     Name  Age       City  Marks  Passed
3    4    Kunal   25    Chennai     50    True
44  45   Sameer   23     Jaipur     50    True
13  14   Sameer   25      Delhi     51    True
4    5    Kabir   18     Jaipur     51    True
14  15    Kunal   30      Delhi     54    True
32  33     Alia   28      Delhi     55    True
9   10    Rahul   18     Jaipur     56    True
28  29    Kunal   26     Mumbai     57    True
10  11    Kunal   21     Jaipur     58    True
39  40    Kabir   22      Delhi     58    True
48  49   Ritesh   28     Mumbai     59    True
37  38     Alia   18     Jaipur     60    True
0    1       Om   18     Jaipur     63    True
1    2    Rohan   23  Bangalore     64    True
19  20  Lavanya   18  Bangalore     66    True
2    3     Pari   20  Bangalore     66    True
12  13    Kabir   19     Jaipur     67    True
36  37    Kabir   22    Kolkata     69    True
34  35    Sanya   24     Jaipur     70    True
47  48   Sameer   28      Delhi     70    True
8    9    Anika   29     Mumbai     70    True
16  17  Lavanya   26  Bangalore     71    True
15  16    Manav   20    Kolkata     72    True
17  18    Kaira   26  Hyderabad     75    True
18  19    Kunal   20  Bangalore     75    True
23  24    Naina   29  Bangalore     76    True
11  12   Nikhil   19    Kolkata     77    True
7    8    Kunal   20    Chennai     77    True
31  32   Simran   29     Jaipur     80    True
21  22    Kabir   28       Pune     81    True
38  39    Rohan   23      Delhi     83    True
25  26    Meera   20      Delhi     84    True
6    7    Rishi   24       Pune     84    True
45  46   Sameer   19     Jaipur     85    True
29  30     Aman   24    Chennai     85    True
43  44    Kaira   29     Jaipur     87    True
24  25    Sanya   20    Chennai     88    True
41  42     Riya   27     Jaipur     88    True
33  34     Aman   27  Hyderabad     89    True
46  47     Sara   27    Kolkata     90    True
27  28    Sneha   23  Bangalore     91    True
49  50     Sara   19  Hyderabad     92    True
5    6     Pari   19    Chennai     94    True
42  43   Nikhil   21       Pune     98    True
35  36    Arjun   19       Pune     99    True
30  31   Vikram   18  Bangalore     99    True
20  21     Mira   28  Bangalore     99    True
22  23    Rehan   19       Pune    100    True
26  27    Arjun   22      Delhi    100    True
40  41    Arjun   21     Jaipur    100    True